src/jp/kelonos/codetrain/dto/UserRequestDto.java
package jp.kelonos.codetrain.dto;

import java.sql.Timestamp;

public class UserRequestDto {

	// 要望ID
	private int id;

	// カテゴリID
	private int category_id;

	// コースID
	private int course_id;

	// 連絡事項
	private String text;

	// 返信済みフラグ
	private boolean repliedFlg;

	// 利用者ID
	private int user_id;

	// 更新日時
	private Timestamp update_time;

	// 更新ユーザ
	private int update_user;

	// 利用者の名前（userテーブルでinner join時に使用）
	private String user_name;

	// 利用者の名前（categoryテーブルでinner join時に使用）
	private String category_name;

	// 利用者の名前（courseテーブルでinner join時に使用）
	private String course_name;

	public String getCategory_name() {
		return category_name;
	}

	public void setCategory_name(String category_name) {
		this.category_name = category_name;
	}

	public String getCourse_name() {
		return course_name;
	}

	public void setCourse_name(String course_name) {
		this.course_name = course_name;
	}

	/**
	 * @return id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id セットする id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return category_id
	 */
	public int getCategory_id() {
		return category_id;
	}

	/**
	 * @param category_id セットする category_id
	 */
	public void setCategory_id(int category_id) {
		this.category_id = category_id;
	}

	/**
	 * @return course_id
	 */
	public int getCourse_id() {
		return course_id;
	}

	/**
	 * @param course_id セットする course_id
	 */
	public void setCourse_id(int course_id) {
		this.course_id = course_id;
	}

	/**
	 * @return text
	 */
	public String getText() {
		return text;
	}

	/**
	 * @param text セットする text
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * @return text[]
	 */
	public String[] getSplitedText() {
		String[] texts =  text.split("\r\n");
        return texts;
    }

	/**
	 * @return repliedFlg
	 */
	public boolean isRepliedFlg() {
		return repliedFlg;
	}

	/**
	 * @param repliedFlg セットする repliedFlg
	 */
	public void setRepliedFlg(boolean repliedFlg) {
		this.repliedFlg = repliedFlg;
	}

	/**
	 * @return user_id
	 */
	public int getUser_id() {
		return user_id;
	}

	/**
	 * @param user_id セットする user_id
	 */
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	/**
	 * @return update_time
	 */
	public Timestamp getUpdate_time() {
		return update_time;
	}

	/**
	 * @param update_time セットする update_time
	 */
	public void setUpdate_time(Timestamp update_time) {
		this.update_time = update_time;
	}

	/**
	 * @return update_user
	 */
	public int getUpdate_user() {
		return update_user;
	}

	/**
	 * @param update_user セットする update_user
	 */
	public void setUpdate_user(int update_user) {
		this.update_user = update_user;
	}

}

src/jp/kelonos/codetrain/controller/AddCustomerServlet.java
package jp.kelonos.codetrain.controller;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jp.kelonos.codetrain.BusinessLogicException;
import jp.kelonos.codetrain.Common;
import jp.kelonos.codetrain.DataSourceManager;
import jp.kelonos.codetrain.SecureRandomPassword;
import jp.kelonos.codetrain.dao.BillingAddressDao;
import jp.kelonos.codetrain.dao.CorpDao;
import jp.kelonos.codetrain.dao.CorpPersonDao;
import jp.kelonos.codetrain.dto.BillingAddressDto;
import jp.kelonos.codetrain.dto.CorpDto;
import jp.kelonos.codetrain.dto.CorpPersonDto;
import jp.kelonos.codetrain.dto.StaffDto;

/**
 * Servlet implementation class AddKnowledgeServlet
 */
@WebServlet("/add-customer")
public class AddCustomerServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	private Logger logger = LoggerFactory.getLogger(AddCustomerServlet.class);

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		logger.info("start:{}", Thread.currentThread().getStackTrace()[1].getMethodName());

		// トップページに遷移する
		Common.logout(Common.OPERATION, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		logger.info("start:{}", Thread.currentThread().getStackTrace()[1].getMethodName());

		HttpSession sess = request.getSession(false);

		if (!Common.isOperatorLoggedIn(sess, response, logger))
			return;

		StaffDto user = (StaffDto) sess.getAttribute("operator");
		if (!user.getAuthority_group().canCreate_corp()) {
			logger.warn("権限なし");
			Common.logout(Common.OPERATION, response);
			return;
		}

		// フォームのデータを取得する
		request.setCharacterEncoding("UTF-8");
		CorpDto corp = new CorpDto();
		corp.setName(request.getParameter("corpName"));
		corp.setDomain(request.getParameter("corpDomain"));
		BillingAddressDto billingAddress = new BillingAddressDto();
		billingAddress.setAddress(request.getParameter("billingAddress"));
		CorpPersonDto corpPerson = new CorpPersonDto();
		corpPerson.setName(request.getParameter("personName"));
		corpPerson.setEmail(request.getParameter("personEmail"));
		corpPerson.setPosition(request.getParameter("personPosition"));

		// 入力チェック
		if ("".equals(corpPerson.getPosition())) {

			sess.setAttribute("errorMessage", "担当者の役職を入力してください");
		}
		if ("".equals(corpPerson.getEmail())) {

			sess.setAttribute("errorMessage", "担当者メールアドレスを入力してください");
		}
		if ("".equals(corpPerson.getName())) {

			sess.setAttribute("errorMessage", "担当者名を入力してください");
		}
		if ("".equals(billingAddress.getAddress())) {

			sess.setAttribute("errorMessage", "請求先住所を入力してください");
		}
		if ("".equals(corp.getDomain())) {

			sess.setAttribute("errorMessage", "ドメインを入力してください");
		}
		if ("".equals(corp.getName())) {

			sess.setAttribute("errorMessage", "法人名を入力してください");
		}

		if (corp.getName().length() > 255 || corp.getDomain().length() > 512 || corpPerson.getEmail().length() > 512
				|| corpPerson.getName().length() > 16 || corpPerson.getPosition().length() > 255
				|| billingAddress.getAddress().length() > 512) {
			sess.setAttribute("errorMessage", "入力文字数が多いです");
		}
		if (sess.getAttribute("errorMessage") != null) {
			// 入力画面に戻る
			request.setAttribute("corpName", corp.getName());
			request.setAttribute("corpDomain", corp.getDomain());
			request.setAttribute("billingAddress", billingAddress.getAddress());
			request.setAttribute("personName", corpPerson.getName());
			request.setAttribute("personEmail", corpPerson.getEmail());
			request.setAttribute("personPosition", corpPerson.getPosition());
			request.getRequestDispatcher("WEB-INF/add-customer.jsp").forward(request, response);
			return;
		}
		String password;
		SecureRandomPassword createPassword = new SecureRandomPassword();
		corp.setUpdate_user(user.getId());
		corpPerson.setUpdate_user(user.getId());
		corpPerson.setPassword(createPassword.createPassword().toString());
		password = corpPerson.getPassword();
		corpPerson.setPasswordsetFlg(false);
		billingAddress.setUpdate_user(user.getId());

		try (Connection conn = DataSourceManager.getConnection()) {

			try {
				CorpDao corpdao = new CorpDao(conn);
				BillingAddressDao billingdao = new BillingAddressDao(conn);
				CorpPersonDao persondao = new CorpPersonDao(conn);

				// トランザクションを開始する
				conn.setAutoCommit(false);

				int nextid;
				int count;

				nextid = persondao.selectAutoIncrement();
				corpPerson.setId(nextid);
				count = persondao.insertWithPrimaryKey(corpPerson);
				if (count == 0)
					throw new BusinessLogicException("排他制御（楽観ロック）例外");

				corp.setCorp_person_id(nextid);
				nextid = corpdao.selectAutoIncrement();
				corp.setId(nextid);
				count = corpdao.insertWithPrimaryKey(corp);
				if (count == 0)
					throw new BusinessLogicException("排他制御（楽観ロック）例外");

				billingAddress.setCorp_id(nextid);
				count = billingdao.insert(billingAddress);
				if (count == 0)
					throw new BusinessLogicException("排他制御（楽観ロック）例外");

				// コミットする
				conn.commit();

			} catch (BusinessLogicException e) {

				logger.error("{} {}", e.getClass(), e.getMessage());

				// ロールバックする
				conn.rollback();
				request.setAttribute("errorMessage", "「" + corp.getName() + "」を登録できませんでした - 排他制御");

				// 法人一覧に遷移する
				request.getRequestDispatcher("list-customer").forward(request, response);
				return;

			} catch (SQLException e) {

				logger.error("{} {}", e.getClass(), e.getMessage());

				// ロールバックする
				conn.rollback();
				throw e;
			} finally {
				conn.setAutoCommit(true);
			}

		} catch (SQLException | NamingException e) {

			logger.error("{} {}", e.getClass(), e.getMessage());

			// システムエラー画面に遷移する
			request.getRequestDispatcher("operation-system-error.jsp").forward(request, response);
			return;
		}

		request.setAttribute("message", "「" + corp.getName() + "」を登録しました 初期パスワードは "+password+" です");
		// チャンネル一覧画面に遷移する
		request.getRequestDispatcher("list-customer").forward(request, response);

	}

}

src/jp/kelonos/codetrain/controller/AddOperatorServlet.java
package jp.kelonos.codetrain.controller;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jp.kelonos.codetrain.Common;
import jp.kelonos.codetrain.DataSourceManager;
import jp.kelonos.codetrain.dao.StaffDao;
import jp.kelonos.codetrain.dto.AuthorityGroupDto;
import jp.kelonos.codetrain.dto.StaffDto;

/**
 * Servlet implementation class AddKnowledgeServlet
 */
@WebServlet("/add-operator")
public class AddOperatorServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	private Logger logger = LoggerFactory.getLogger(AddOperatorServlet.class);

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		logger.info("start:{}", Thread.currentThread().getStackTrace()[1].getMethodName());

		// トップページに遷移する
		Common.logout(Common.OPERATION, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		logger.info("start:{}", Thread.currentThread().getStackTrace()[1].getMethodName());

		HttpSession sess = request.getSession(false);

		if (!Common.isOperatorLoggedIn(sess, response, logger))
			return;

		StaffDto user = (StaffDto) sess.getAttribute("operator");
		if (!user.getAuthority_group().canCreate_operator()) {
			logger.warn("権限なし");
			Common.logout(Common.OPERATION, response);
			return;
		}

		// フォームのデータを取得する
		request.setCharacterEncoding("UTF-8");
		StaffDto newStaff = new StaffDto();
		AuthorityGroupDto authority = new AuthorityGroupDto();
		try {
			authority.setId(Integer.parseInt(request.getParameter("authority_id")));
		} catch (Exception e) {
			e.printStackTrace(System.out);
			Common.logout(Common.OPERATION, response);
			return;
		}
		if (authority.getId() < 1) {
			Common.logout(Common.OPERATION, response);
			return;
		}

		newStaff.setName(request.getParameter("name"));
		newStaff.setLogin_id(request.getParameter("login_id"));
		newStaff.setPassword(request.getParameter("password"));
		newStaff.setAuthority_group(authority);

		sess.removeAttribute("errorMessage");
		sess.removeAttribute("message");

		// 入力チェック
		if (request.getParameter("password") == null || request.getParameter("password_confirm") == null
				|| "".equals(request.getParameter("password")) || "".equals(request.getParameter("password_confirm"))) {
			sess.setAttribute("errorMessage", "パスワード、確認用パスワードを入力してください");
		} else if (!request.getParameter("password").equals(request.getParameter("password_confirm"))) {
			sess.setAttribute("errorMessage", "パスワードが確認用パスワードと一致しません");
		}
		if (newStaff.getLogin_id() == null || "".equals(newStaff.getLogin_id())) {
			sess.setAttribute("errorMessage", "ログインIDを入力してください");
		}
		if (newStaff.getName() == null || "".equals(newStaff.getName())) {
			sess.setAttribute("errorMessage", "氏名を入力してください");
		}

		if (newStaff.getLogin_id().length() > 255 || newStaff.getPassword().length() > 16
				|| newStaff.getName().length() > 16) {
			sess.setAttribute("errorMessage", "入力文字数が多いです");
		}
		if (sess.getAttribute("errorMessage") != null) {
			// 入力画面に戻る
			sess.setAttribute("name", newStaff.getName());
			sess.setAttribute("login_id", newStaff.getLogin_id());
			sess.setAttribute("authority_group_id", authority.getId());
			response.sendRedirect("register-operator");
			return;
		}

		newStaff.setUpdate_user(user.getId());
		newStaff.setPasswordsetFlg(false);

		// コネクションを取得する
		try (Connection conn = DataSourceManager.getConnection()) {

			// チャンネル一覧を取得する
			StaffDao dao = new StaffDao(conn);

			dao.insert(newStaff, user.getId());

			// URIをリクエストに保持する
			request.setAttribute("uri", request.getRequestURI());

		} catch (SQLException | NamingException e) {

			logger.error("{} {}", e.getClass(), e.getMessage());

			// システムエラー画面に遷移する
			request.getRequestDispatcher("operation-system-error.jsp").forward(request, response);
			return;
		}

		sess.setAttribute("message", "「" + newStaff.getName() + "」さんを登録しました");
		// 運用管理者一覧画面に遷移する
		response.sendRedirect("list-operator");

	}

}

src/jp/kelonos/codetrain/controller/ListCustomerServlet.java
package jp.kelonos.codetrain.controller;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.naming.NamingException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jp.kelonos.codetrain.Common;
import jp.kelonos.codetrain.DataSourceManager;
import jp.kelonos.codetrain.dao.CorpDao;
import jp.kelonos.codetrain.dto.CorpDto;
import jp.kelonos.codetrain.dto.StaffDto;

/**
 * Servlet implementation class ThreadListServlet
 */
@WebServlet("/list-customer")
public class ListCustomerServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	private Logger logger = LoggerFactory.getLogger(ListCustomerServlet.class);

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		logger.info("start:{} {}", Thread.currentThread().getStackTrace()[1].getMethodName(), request.getRemoteAddr());

		HttpSession sess = request.getSession(false);
		if (!Common.isOperatorLoggedIn(sess, response, logger)) return;

		StaffDto user = (StaffDto)sess.getAttribute("operator");
		if (!user.getAuthority_group().canShow_corplist()) {
			logger.warn("権限なし");
			Common.logout(Common.OPERATION, response);
			return;
		}

		// コネクションを取得する
		try (Connection conn = DataSourceManager.getConnection()) {
			// セッションを取得する
			HttpSession session = request.getSession(true);
			session.removeAttribute("queries");

			// チャンネル一覧を取得する
			CorpDao dao = new CorpDao(conn);
			ArrayList<CorpDto> list = dao.selectAll();

			// チャンネル一覧データをリクエストに保持する
			request.setAttribute("corpList", list);

			// URIをリクエストに保持する
			request.setAttribute("uri", request.getRequestURI());

			// チャンネル一覧画面に遷移する
			request.getRequestDispatcher("WEB-INF/list-customer.jsp").forward(request, response);
		} catch (SQLException | NamingException e) {

			logger.error("{} {}", e.getClass(), e.getMessage());

			// システムエラー画面に遷移する
			request.getRequestDispatcher("operation-system-error.jsp").forward(request, response);
			return;
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}

WebContent/WEB-INF/customer-navbar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<link rel="stylesheet" type="text/css" href="./css/navbar.css">
<nav class="navbar navbar-expand-lg navbar-light customer">
	<a class="navbar-brand" href="list-user"><img
		src="img/CodeTrain.png" height="50" width="72" /></a>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<form action="list-user" method="post" class="form-inline">
					<button type="submit" class="btn btn-outline-primary btn-sm ml-2">利用者一覧</button>
				</form>
			</li>
			<li>
				<form action="manage-user" method="post">
					<button class="btn btn-outline-primary btn-sm ml-2">利用者登録/休止</button>
				</form>
			</li>
			<li>
				<form action="show-billing" method="post">
					<button class="btn btn-outline-primary btn-sm ml-2">請求確認</button>
				</form>
			</li>
		</ul>
		<div class="navbar-text small mr-3 text-secondary">
			<c:out
				value="${ not empty customer.name ? customer.name += 'さん、こんにちは' : '' }" />
		</div>
		<form action="customer-change-password" method="post"
			class="form-inline">
			<input type="hidden" name="id" value="${ customer.id }"> <input
				type="hidden" name="login-now" value="1">
			<button type="submit" class="btn btn-outline-secondary btn-sm">パスワード変更</button>
		</form>
		<form action="logout" method="post" class="form-inline">
			<button type="submit" class="btn btn-outline-danger btn-sm ml-2">ログアウト</button>
		</form>

	</div>
</nav>

WebContent/WEB-INF/header.jsp
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

WebContent/WEB-INF/list-message.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><c:out value="${userName}" />さんと連絡</title>
<script type="text/javascript">
	<!--
		var old_form_id = 0;
		function submitConfirm() {
			return window.confirm("この内容で送信してよろしいでしょうか？");
		}
		function resetConfirm() {
			return window.confirm("内容をクリアしますがよろしいですか？");
		}
		function selectUserRequest(id) {

			if (old_form_id == id) return;

			const hidden_reqeust_id = document.getElementsByName('request_id')[0];
			hidden_reqeust_id.setAttribute("value", id);

			var idkey = 'replyform_' + old_form_id;
			const oldform = document.getElementById(idkey);

			idkey = 'replyform_' + id;
			const target = document.getElementById(idkey);

			//target.appendChild(oldform);
			//oldform.removeChild(oldform.firstChild);
			target.innerHTML = oldform.innerHTML;
			oldform.innerHTML = '';
			old_form_id = id;

		}
	// -->
	</script>
<%@ include file="header.jsp"%>
<link rel="stylesheet" type="text/css" href="./css/user_request.css">
</head>
<body>
	<%@ include file="operation-navbar.jsp"%>
	<div class="container" style="margin-bottom: 50px">

		<div class="row">
			<div class="col-12">
				<p style="position: relative">
					<p class="h4 mt-3 p-3 bg-light text-info rounded"><c:out
							value="${userName}" />さんと連絡</p>
							 <span class="text-danger"
						style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
						<c:out value="${ errorMessage }" /> <%
 	session.removeAttribute("errorMessage");
 %>
					</span>
					 <span class="text-danger"
						style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
						<c:out value="${ message }" /> <%
 	session.removeAttribute("message");
 %>
					</span>
				</p>
				<div class="row">
					<div class="col" id="replyform_0">
						<form action="add-reply" method="post" class="form-group">
							<!-- 入力フォーム -->
							<input type="hidden" name="request_id"
								value="${requestList.get(0).id}" /> <input type="hidden"
								name="user_id" value="${userId}" /> <label
								class="col-form-label"><c:out value="${userName}" />さんへ返信</label>
							<textarea name="text" class="form-control" maxlength="65535"
								autofocus="autofocus" rows="4"><c:out
									value="${reply_text}" /></textarea>
									<% session.removeAttribute("reply_text"); %>
							<button type="submit" class="btn btn-success float-right"
								style="margin-top: 5px" onclick="return submitConfirm()">送信</button>
						</form>
					</div>
				</div>
				<c:forEach items="${requestList}" var="req">
					<div class="row" style="margin-top: 10px">
						<div class="col-12">
							<!-- 利用者からの連絡 -->
							<div class="card float-left user_request" style="width: 95%"
								onclick="selectUserRequest(${req.id})">
								<c:if test="${not req.repliedFlg}">
									<div style="border: 2px solid rgba(255, 0, 0, 0.3)">
								</c:if>
								<div class="card-body"
									style="padding-top: 5px; padding-bottom: 5px;">
									<div class="card-title"
										style="position: relative; margin-bottom: 5px;">
										<c:if test="${not req.repliedFlg}">
											<span class="badge badge-danger"
												style="position: absolute; top: 0%; left: 0%; transform: translate(-100%, -50%);">未返信</span>
										</c:if>
										<span class="text-info" style="">カテゴリ：<c:out
												value="${req.category_name}" /></span> <br> <span
											class="text-info" style="">コース：<c:out
												value="${req.course_name}" /></span> <span class="text"
											style="position: absolute; top: 50%; right: 0%; transform: translate(0, -50%);">
											日時：<c:out value="${req.update_time}" />
										</span>
									</div>
									<p class="card-text">
										<c:forEach var="reqStr" items="${req.splitedText}">
											<c:out value="${reqStr}" />
											<br>
										</c:forEach>
									</p>
								</div>
								<c:if test="${not req.repliedFlg}">
							</div>
							</c:if>
						</div>
					</div>
					<div class="col-12" id="replyform_${req.id}"></div>
					<c:forEach items="${replyMap.get(req.id)}" var="reply">
						<div class="col-12">
							<!-- 利用者への返信 -->
							<div class="card float-right"
								style="width: 95%; background: linear-gradient(-45deg, rgba(161, 246, 246, 0.1), rgba(161, 161, 246, 0.1));">
								<div class="card-body"
									style="padding-top: 5px; padding-bottom: 5px;">
									<div class="card-title"
										style="position: relative; margin-bottom: 5px;">
										<span class="text-info" style="">返信者：<c:out
												value="${reply.staff_name}" /></span> <span class="text"
											style="position: absolute; top: 50%; right: 0%; transform: translate(0, -50%);">
											日時：<c:out value="${reply.update_time}" />
										</span>
									</div>
									<p class="card-text">
										<c:forEach var="replyStr" items="${reply.splitedText}">
												<c:out value="${replyStr}" />
												<br>
										</c:forEach>
									</p>
								</div>
							</div>
						</div>
					</c:forEach>
			</div>
			</c:forEach>
		</div>
	</div>
	</div>
</body>
</html>

WebContent/WEB-INF/list-user.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>利用者一覧</title>
<%@ include file="header.jsp"%>
</head>
<body>
	<%@ include file="customer-navbar.jsp"%>
	<div class="container">
		<div class="row">
			<div class="col-12">
				<p class="h4 mt-3 p-3 bg-light text-info rounded">利用者一覧</p>
				<table class="table table-striped" style="margin-top:35px">
					<thead>
						<tr>
							<th scope="col">社員番号</th>
							<th scope="col">氏名</th>
							<th scope="col">状態</th>
							<th scope="col">詳細</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${user}" var="dto">
							<tr>
								<td><c:out value="${ dto.getEmpno() }" /></td>
								<td><c:out value="${ dto.name }" /></td>
								<c:choose>
										<c:when test="${dto.state eq 0 }">
											<td><span class="badge badge-success">アクティブ</span></td>
										</c:when>
										<c:otherwise>
											<td><span class="badge badge-dark">休止</span></td>
										</c:otherwise>
									</c:choose>
								<td>
									<form action="view-user" method="post">
										<input type="hidden" name="id" value="${ dto.id }">
										<button type="submit" class="btn btn-primary btn-sm">詳細</button>
									</form>
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</body>
</html>